/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //  dirName: '.'表示使用当前的文档文件夹
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 2022/1/28 每个分类使用自己的侧边栏
  minigameSidebar: [{type: 'autogenerated', dirName: 'minigame'}],
  appgameSidebar: [{type: 'autogenerated', dirName: 'appgame'}],
  testSidebar: [{type: "autogenerated", dirName:"testgame"}]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
